/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/webview/app/theme/mdreadrTheme.ts
 * Command: astryx theme build src/webview/app/theme/mdreadrTheme.ts --out src/webview/app/theme/mdreadr.css
 * Generated: 2026-07-15T20:42:12.640Z
 */

/// <reference path="./mdreadr.variants.d.ts" />
import type { DefinedTheme } from "@astryxdesign/core/theme";
export declare const mdreadrTheme: DefinedTheme;
