/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/webview/app/theme/mdreadrTheme.ts
 * Command: astryx theme build src/webview/app/theme/mdreadrTheme.ts --out src/webview/app/theme/mdreadr.css
 * Generated: 2026-07-15T12:02:36.540Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
